Repository apache/openwhisk-runtime-php, pull requests merged in 2018-05, with the labels that each got.

#14 Add the license of dependencies into LICENSE file
  LICENSE.txt
  licenses/LICENSE-bcmath.txt
  licenses/LICENSE-dockerphpext.txt
  licenses/LICENSE-gd.txt
  licenses/LICENSE-intl.txt
  licenses/LICENSE-mysqli.txt
  licenses/LICENSE-opcache.txt
  licenses/LICENSE-pdomysql.txt
  licenses/LICENSE-pdopgsql.txt
  licenses/LICENSE-php.txt
  licenses/LICENSE-soap.txt
  licenses/LICENSE-zip.txt
Labels: review

#19 Add ASF license headers to all Scala .conf files.
  .scalafmt.conf
  tests/src/test/resources/application.conf
Labels: apache

#20 Fix markdown files with a typo. in the Hash license header.
  CONTRIBUTING.md
  README.md
  gradle/README.md
Labels: apache, documentation

#22 Fix travis yaml file asf header, change to mini.
  .travis.yml
Labels: apache, review

#24 Fix bad Dockerfile license and use ASF release config.
  core/php7.1Action/Dockerfile
  tools/travis/build.sh
Labels: apache
